In [1]:
import torch
import numpy as np

# Initializing a Tendor

#### Directly from data
torch.tensor(2D_dim_array)

In [2]:
data = [[10, 25], [19, 33]]
x_data = torch.tensor(data)

#### From a numpy array
torch.from_numpy(np_array)

In [3]:
np_array = np.array(data)
x_np = torch.from_numpy(np_array)

#### From another tensor 

In [4]:
# retains the properties of x_data
x_ones = torch.ones_like(x_data) 
print(f"Ones Tensor: \n {x_ones} \n")

# overrides the datatype of x_data
x_rand = torch.rand_like(x_data, dtype=torch.float)
print(f"Random Tensor: \n {x_rand} \n")

Ones Tensor: 
 tensor([[1, 1],
        [1, 1]]) 

Random Tensor: 
 tensor([[0.4630, 0.9707],
        [0.1944, 0.9002]]) 


#### With random or constant values:
shape is a tuple of tensor dim

In [5]:
shape = (2,3)
# 產生隨機 2x3
rand_tensor = torch.rand(shape)
# 產生都是1 2x3
ones_tensor = torch.ones(shape)
# 產生都是0 2x3
zeros_tensor = torch.zeros(shape)

print(f"Random Tensor: \n {rand_tensor} \n")
print(f"Ones Tensor: \n {ones_tensor} \n")
print(f"Zeros Tensor: \n {zeros_tensor} \n")

Random Tensor: 
 tensor([[0.7705, 0.9783, 0.1767],
        [0.6734, 0.2424, 0.8285]]) 

Ones Tensor: 
 tensor([[1., 1., 1.],
        [1., 1., 1.]]) 

Zeros Tensor: 
 tensor([[0., 0., 0.],
        [0., 0., 0.]]) 


# Attributes of a Tensor

In [6]:
tensor = torch.rand(3,4)

print(f"Shape of tensor: {tensor.shape}")
print(f"Datatype of tensor: {tensor.dtype}")
print(f"Device tensor is stored on: {tensor.device}")

# # cpu -> gpu
# device = (
#     "cuda"
#     if torch.cuda.is_available()
#     else "mps"
#     if torch.backends.mps.is_available()
#     else "cpu"
# )
# gpu_tensor = tensor.to(device)
# print(f"Device tensor is stored on: {gpu_tensor.device}")

Shape of tensor: torch.Size([3, 4])
Datatype of tensor: torch.float32
Device tensor is stored on: cpu


# Operations on Tensors

In [7]:
# move tensor to the GPU if available
if torch.cuda.is_available():
    tensor = tensor.to("cuda")

#### Standard numpy-like indexing and slicing:

In [8]:
# tensor = torch.rand(2,3)
tensor = torch.ones(4,4)
# tensor = torch.rand(4,4)
print(f"tensor: \n {tensor}\n")
print(f"First row: \n {tensor[0]}\n")
# [row, col]
print(f"First column: \n {tensor[:, 0]}\n")
# print(f"Last column: {tensor[..., -1]}")
print(f"Last column: \n {tensor[:, -1]}\n")
# 將第二行全部設為0
tensor[:, 1] = 0
print(tensor)

tensor: 
 tensor([[1., 1., 1., 1.],
        [1., 1., 1., 1.],
        [1., 1., 1., 1.],
        [1., 1., 1., 1.]])

First row: 
 tensor([1., 1., 1., 1.])

First column: 
 tensor([1., 1., 1., 1.])

Last column: 
 tensor([1., 1., 1., 1.])

tensor([[1., 0., 1., 1.],
        [1., 0., 1., 1.],
        [1., 0., 1., 1.],
        [1., 0., 1., 1.]])


In [9]:
# Joining tensors
# 以col方式
t1 = torch.cat([tensor, tensor, tensor], dim=1)
print(f"t1: \n {t1}")

# 以row方式
# t2 = torch.cat([tensor, tensor, tensor], dim=0)
# print(t2)

t1: 
 tensor([[1., 0., 1., 1., 1., 0., 1., 1., 1., 0., 1., 1.],
        [1., 0., 1., 1., 1., 0., 1., 1., 1., 0., 1., 1.],
        [1., 0., 1., 1., 1., 0., 1., 1., 1., 0., 1., 1.],
        [1., 0., 1., 1., 1., 0., 1., 1., 1., 0., 1., 1.]])


In [10]:
# 陣列相乘 (tensor.T 轉置)
# This computes the matrix multiplication between two tensors. y1, y2, y3 will have the same value
# ``tensor.T`` returns the transpose of a tensor
# y = T x T'
y1 = tensor @ tensor.T
print(f"y1: \n {y1}")

y2 = tensor.matmul(tensor.T)
print(f"y2: \n {y2}")

# 複製y1格式
y3 = torch.rand_like(y1)
# 陣列相乘後放入y3
torch.matmul(tensor, tensor.T, out=y3)# T*T'
print(f"y3: \n {y3}")

# This computes the element-wise product. z1, z2, z3 will have the same value
# y = T. * T.
z1 = tensor * tensor
print(f"z1: \n {z1}")
z2 = tensor.mul(tensor)# T.*T.
print(f"z2: \n {z2}")
z3 = torch.rand_like(tensor)
torch.mul(tensor, tensor, out=z3)#T.*T.
print(f"z3: \n {z3}")

y1: 
 tensor([[3., 3., 3., 3.],
        [3., 3., 3., 3.],
        [3., 3., 3., 3.],
        [3., 3., 3., 3.]])
y2: 
 tensor([[3., 3., 3., 3.],
        [3., 3., 3., 3.],
        [3., 3., 3., 3.],
        [3., 3., 3., 3.]])
y3: 
 tensor([[3., 3., 3., 3.],
        [3., 3., 3., 3.],
        [3., 3., 3., 3.],
        [3., 3., 3., 3.]])
z1: 
 tensor([[1., 0., 1., 1.],
        [1., 0., 1., 1.],
        [1., 0., 1., 1.],
        [1., 0., 1., 1.]])
z2: 
 tensor([[1., 0., 1., 1.],
        [1., 0., 1., 1.],
        [1., 0., 1., 1.],
        [1., 0., 1., 1.]])
z3: 
 tensor([[1., 0., 1., 1.],
        [1., 0., 1., 1.],
        [1., 0., 1., 1.],
        [1., 0., 1., 1.]])


#### Single-element tensors

In [11]:
# 所有element加起來
agg = tensor.sum()
print(f"agg: \n {agg}\n")
agg_item = agg.item()
print(f"agg_item: \n {agg_item} \ntype: \n {type(agg_item)}\n")

agg: 
 12.0

agg_item: 
 12.0 
type: 
 <class 'float'>


#### In-place operations

In [12]:
print(f"tensor: \n{tensor}\n")
# 每個element + 5 然後數值直接在原始陣列上加
tensor.add_(5)
print(f"tensor.add_(5): \n{tensor}")

tensor: 
tensor([[1., 0., 1., 1.],
        [1., 0., 1., 1.],
        [1., 0., 1., 1.],
        [1., 0., 1., 1.]])

tensor.add_(5): 
tensor([[6., 5., 6., 6.],
        [6., 5., 6., 6.],
        [6., 5., 6., 6.],
        [6., 5., 6., 6.]])


# Bridge with numpy

#### Tensor to numpy array

In [13]:
t = torch.ones(5) # 1x5
print(f"t: \n {t}\n")
n = t.numpy()
print(f"n: \n {n}\n")

t: 
 tensor([1., 1., 1., 1., 1.])

n: 
 [1. 1. 1. 1. 1.]


In [14]:
t.add_(1)
print(f"t: \n {t}\n")
print(f"n: \n {n}\n")

t: 
 tensor([2., 2., 2., 2., 2.])

n: 
 [2. 2. 2. 2. 2.]


# numpy array to Tensor

In [15]:
n = np.ones(5) # 1x5
t = torch.from_numpy(n)
print(f"n: \n {n}\n")
print(f"t: \n {t}\n")

n: 
 [1. 1. 1. 1. 1.]

t: 
 tensor([1., 1., 1., 1., 1.], dtype=torch.float64)


In [16]:
np.add(n, 1, out=n)
print(f"t: \n {t}\n")
print(f"n: \n {n}\n")

t: 
 tensor([2., 2., 2., 2., 2.], dtype=torch.float64)

n: 
 [2. 2. 2. 2. 2.]
